package com.moonlightqz.mymall.mapper;

import com.moonlightqz.mymall.mbg.model.PmsBrandExample;
import com.moonlightqz.mymall.entity.PmsBrand;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PmsBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    long countByExample(PmsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    boolean deleteByExample(PmsBrandExample example);

    boolean deleteByPrimaryKey(Long id);

    boolean insert(PmsBrand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int insertSelective(PmsBrand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    List<PmsBrand> selectByExampleWithBLOBs(PmsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    List<PmsBrand> selectByExample(PmsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    PmsBrand selectByPrimaryKey(Long id);


    boolean updateByExampleSelective(@Param("row") PmsBrand row, @Param("example") PmsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") PmsBrand row, @Param("example") PmsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByExample(@Param("row") PmsBrand row, @Param("example") PmsBrandExample example);


    boolean updateByPrimaryKeySelective(PmsBrand row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_brand
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PmsBrand row);

    int updateByPrimaryKey(PmsBrand row);
}