package com.moonlightqz.mymall.mbg.mapper;

import com.moonlightqz.mymall.mbg.model.CmsSubject;
import com.moonlightqz.mymall.mbg.model.CmsSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    long countByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int deleteByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int insert(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int insertSelective(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    List<CmsSubject> selectByExampleWithBLOBs(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    List<CmsSubject> selectByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    CmsSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByExampleSelective(@Param("row") CmsSubject row, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") CmsSubject row, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByExample(@Param("row") CmsSubject row, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByPrimaryKeySelective(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(CmsSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbg.generated Wed May 10 16:50:35 CST 2023
     */
    int updateByPrimaryKey(CmsSubject row);
}